Cleaned up, added with documentation on config info.
CalPolyFSAE/MKELibrary pull request #13
Opened 2021-11-18 04:05 UTC by pron3211

i think it works (key word think)

2021-11-27 02:10 UTC, BaylorWhitehead requested changes
Also remove the .eld and libbsp.a file. Also look at other comments

2021-11-27 02:10 UTC, BaylorWhitehead commented on SConstruct
> -GNU_PATH = SConscript('config.txt')
Revert this

2021-11-27 02:10 UTC, BaylorWhitehead commented on template/generic/board/can.h
> +/*
Remove this whole file

2021-11-27 02:10 UTC, BaylorWhitehead commented on template/generic/source/main2.cpp
> +#include "MKE18F16.h"
Remove this whole file

2021-11-30 02:49 UTC, pron3211 commented
good?

2021-11-30 03:07 UTC, BaylorWhitehead approved these changes

2021-11-30 03:07 UTC, merged